### PR TITLE
Cherry-pick #46 to jammy (try checking out ci_matching_branch for gzdev)

### PR DESCRIPTION
**Pull request by scpeters**
Cherry-pick of #46 to jammy branch. Use rebase-and-merge.

### CODE REVIEW

**Review by chapulina — APPROVED** [review]

**Comment by scpeters** [comment]
I recommended rebase-and-merge, but it's not a big deal

**Comment by chapulina** [comment]
Ouch sorry, fast fingers. I always assumed that squash and rebase did the same thing when there's only one commit

**Comment by scpeters** [comment]
rebase keeps the original commit message, while squash and merge appends an extra PR reference number, which is maybe what you want; it depends I suppose. Not a huge difference either way though

**Comment by chapulina** [comment]
> rebase keeps the original commit message, while squash and merge appends an extra PR reference number, which is maybe what you want; it depends I suppose. Not a huge difference either way though

Ahh makes sense 👍🏽 Thanks for the clarification.

**Pull request merged**
