### PR TITLE
Update focal to use gcc9

### PR DESCRIPTION
**Pull request by mjcarroll**
Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by chapulina** [comment]
I believe the test run in https://github.com/ignitionrobotics/ign-fuel-tools/pull/230 didn't have coverage enabled, it would be nice to test that LCOV is working as expected with this change

**Comment by scpeters** [comment]
this is needed for jammy

https://github.com/ignitionrobotics/sdformat/runs/5858181025?check_suite_focus=true

**Comment by chapulina** [comment]
Has anyone triggered a test run using this branch which has coverage enabled? I just wanna make sure we don't break the coverage jobs

**Comment by scpeters** [comment]
> Has anyone triggered a test run using this branch which has coverage enabled? I just wanna make sure we don't break the coverage jobs

trying it now with https://github.com/ignitionrobotics/ign-math/commit/1f6703cd08f2c4685ae1c0b3ecddb5df1a300841

* https://github.com/ignitionrobotics/ign-math/runs/5862490338?check_suite_focus=true

**Review by chapulina — APPROVED** [review]
The test run was successful!

**Comment by azeey** [comment]
Coverage seems to be broken in some (if not all) our libraries. In sdformat PR [#939](https://github.com/ignitionrobotics/sdformat/pull/939), for example, the number of tracked files is now just 2:
image
whereas, about a month ago (eg https://github.com/ignitionrobotics/sdformat/pull/909), the number of files was 69:
image

I suspect removing the `lcov` related lines might have caused the issue, but I'm not 100% sure.

**Comment by scpeters** [comment]
> > Has anyone triggered a test run using this branch which has coverage enabled? I just wanna make sure we don't break the coverage jobs
> 
> trying it now with [ignitionrobotics/ign-math@1f6703c](https://github.com/ignitionrobotics/ign-math/commit/1f6703cd08f2c4685ae1c0b3ecddb5df1a300841)
> 
> * https://github.com/ignitionrobotics/ign-math/runs/5862490338?check_suite_focus=true

it looks like the GitHub action didn't passed the status check but didn't generate a proper coverage report

* https://app.codecov.io/gh/ignitionrobotics/ign-math/branch/scpeters%2Faction_focal_gcc9

**Comment by azeey** [comment]
> it looks like the GitHub action didn't passed the status check but didn't generate a proper coverage report

> > https://app.codecov.io/gh/ignitionrobotics/ign-math/branch/scpeters%2Faction_focal_gcc9

That actually looks okay to me (https://codecov.io/gh/ignitionrobotics/ign-math/tree/1f6703cd08f2c4685ae1c0b3ecddb5df1a300841). The project totals show 70 files, which is 2 more than a random PR I picked from 2 moths ago.

**Comment by azeey** [comment]
Okay, this might actually be caused by the Checkout action due to https://github.com/actions/checkout/pull/764. I think what's happening is that codecov tries to determine the project root using `git` (https://github.com/codecov/codecov-bash/blob/1817ab23d6b35ff6596e48d15db366b71f17ada3/codecov#L48), but fails due to how the repo is checkout as of https://github.com/actions/checkout/pull/764. We can see this when comparing the console output of codecov for a failed and successful report generation:

**Failed report generation** (https://github.com/ignitionrobotics/sdformat/runs/6244787092?check_suite_focus=true)
```
  current dir:  /github/workspace/build
  project root: .

```
**Successful report generation** (https://github.com/ignitionrobotics/sdformat/runs/5565309483?check_suite_focus=true)
```
  current dir:  /github/workspace/build
  project root: /github/workspace
```

My suggestion would be to `cd` into the root and run `codecov` from there with a flag to tell it where to find the `coverage.info` file.

**Pull request merged**
