### PR TITLE
Update jammy to not use gcc-8

### PR DESCRIPTION
**Pull request by scpeters**
Copy of #50 targeting jammy. This is needed to fix Jammy CI:

* https://github.com/ignitionrobotics/sdformat/runs/5858181025?check_suite_focus=true

Depends on #53

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]
LGTM. Just a note that `jammy` will be `gcc-11`, if I recall correctly.

**Comment by scpeters** [comment]
> LGTM. Just a note that `jammy` will be `gcc-11`, if I recall correctly.

I updated the PR title accordingly

**Comment by chapulina** [comment]
Same thing as #50, can we trigger a build that has coverage enabled and uses this branch?

**Comment by chapulina** [comment]
We don't have coverage running for any libs on Jammy yet, I believe, so let's deal with that later

**Review by chapulina — APPROVED** [review]

**Pull request merged**
